version: '3'
services:
    postgres:
        image: postgres:17-alpine
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/config:/etc/postgresql
        environment:
            - POSTGRES_DB=gobase
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=developer
        ports:
            - 5432:5432
        networks:
            - net

    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - net

networks:
    net:
        driver: bridge