# Пример конфигурационного файла
# Скопируйте этот файл в config.yaml и настройте под свои нужды

db:
  dsn: "postgresql://developer:developer@localhost:5432/gobase?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5

app:
  run_addr: "localhost:8080"

rabbitmq:
  # URL подключения к RabbitMQ (amqp://username:password@host:port/vhost)
  url: "amqp://guest:guest@localhost:5672/"