basePath: /
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: REST API для GoBase проекта
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: GoBase API
  version: "1.0"
paths:
  /ping:
    get:
      description: Проверяет доступность сервиса и подключение к базе данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Service unhealthy
          schema:
            additionalProperties: true
            type: object
      summary: Проверка здоровья сервиса
      tags:
      - healthcheck
schemes:
- http
- https
swagger: "2.0"
